<?php
$a_category =  array(
'1'=>array(
'categoryid'=>'1',
'title'=>'Vile din lemn',
'description'=>'Diverse Chalet-uri si cabane',
'content'=>'<p>&nbsp;Diverse vile si cabane realizate in Franta, Spania, Italia si Romania.</p>',
'tag'=>'vila lemn, cabana lemn',
'directory'=>'vile',
'image'=>'',
'footer'=>'',
'header'=>'',
'domainid'=>'1',
'active'=>'1',
'home'=>'0',
'ordon'=>'1',
'total'=>'295',
'google'=>'0',
'articles'=>'3',
),
'3'=>array(
'categoryid'=>'3',
'title'=>'Chalet-uri',
'description'=>'Chalet-uri este un termen elvetian',
'content'=>'<p>&nbsp;Chalet-uri este un termen elvetian, care descrie o vila din lemn conceputa in stil elvetian.</p>',
'tag'=>'chalet, elvetian',
'directory'=>'vile',
'image'=>'',
'footer'=>'',
'header'=>'',
'domainid'=>'1',
'active'=>'1',
'home'=>'0',
'ordon'=>'2',
'total'=>'14',
'google'=>'0',
'articles'=>'0',
),
'2'=>array(
'categoryid'=>'2',
'title'=>'Casute lemn',
'description'=>'Gama larga de  casute din lemn.',
'content'=>'<p>&nbsp;Producem deasemenea o gama larga de casute din lemn foarte frumoase si cu bun gust.</p>',
'tag'=>'casute lemn',
'directory'=>'casute',
'image'=>'',
'footer'=>'',
'header'=>'',
'domainid'=>'1',
'active'=>'1',
'home'=>'0',
'ordon'=>'3',
'total'=>'10',
'google'=>'0',
'articles'=>'0',
),
'4'=>array(
'categoryid'=>'4',
'title'=>'Bungalow-uri',
'description'=>'Bungalow-ul  este un tip de casa aparut la sfarsitul secolului 19...',
'content'=>'<p>&nbsp;<span style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: small; line-height: 15px;">Bungalow-ul &nbsp;este un tip de casa aparut la sfarsitul secolului 19 si este caracterizat prin urmatoarele: aproape toate camerele sunt construite la nivelul terenului, acoperisul are inclinatia mica, camera de zi sau sufrageria este asezata in mijlocul constructiei, incaperile sunt legate prin holuri si exista multe spatii cu rafturi pentru depozitare si, neaparat, o veranda deschisa sau inchisa cu coloane sau stalpi patrati. Forma casei este special aleasa pentru a suporta caldurile mari vara si a oferi protectie termica iarna.&nbsp;</span></p>',
'tag'=>'bungalow, secolul 19',
'directory'=>'casute',
'image'=>'',
'footer'=>'',
'header'=>'',
'domainid'=>'1',
'active'=>'1',
'home'=>'0',
'ordon'=>'4',
'total'=>'3',
'google'=>'0',
'articles'=>'0',
),
);?>