<?php
$a_page =  array(
'home'=>array(
'pageid'=>'1',
'name'=>'home',
'template'=>'home',
'menu'=>'Acasa',
'title'=>'Producem si comercializam o variata gama de constructii din lemn.',
'description'=>'Firma noastra a luat fiinta acum 14 ani la Cluj-Napoca, Romania, oras inconjurat de bogate regiuni forestiere si cu o puternica industrie de prelucrare a lemnului.',
'content'=>'<p><b>Firma noastra a luat fiinta acum 14 ani la Cluj-Napoca, Romania, oras inconjurat de bogate regiuni forestiere si cu o puternica industrie de prelucrare a lemnului.</b></p>',
'tag'=>'cluj, cluj-napoca',
'header'=>'',
'footer'=>'Avand o veche traditie in arta prelucrarii lemnului, specializarea noastra este domeniul fabricarii si montarii caselor din lemn.
Firma noastra ofera solutii la cheie in orice tipuri
constructii din lemn: casute, case cabane si vile',
'domainid'=>'1',
'menus'=>'top|bottom',
'active'=>'1',
'home'=>'1',
'total'=>'0',
'link'=>'',
'ordon'=>'1',
),
'produsenoi'=>array(
'pageid'=>'6',
'name'=>'produsenoi',
'template'=>'new',
'menu'=>'Produse noi',
'title'=>'Produse & Articole Noi',
'description'=>'Cele mai noi produse si articole oferite de [config_title]. [config_title] va ofera o diversitate larga de produse prin gama variata de nuante si materiale ce cu siguranta vor intregi atmosfera locuintei dumneavoastra. Firma noastra este localizata in orasul Cluj-Napoca, judetul Cluj.',
'content'=>'<p>Cele mai noi produse si articole oferite de <strong>[config_title]</strong>. <strong>[config_title] </strong>va ofera o diversitate larga de produse prin gama variata de nuante si materiale ce cu siguranta vor intregi atmosfera locuintei dumneavoastra. Firma noastra este localizata in orasul Cluj-Napoca, judetul Cluj.</p>',
'tag'=>'produse',
'header'=>'',
'footer'=>'',
'domainid'=>'1',
'menus'=>'top',
'active'=>'1',
'home'=>'0',
'total'=>'0',
'link'=>'',
'ordon'=>'2',
),
'celemaibuneproduse'=>array(
'pageid'=>'5',
'name'=>'celemaibuneproduse',
'template'=>'best',
'menu'=>'Cele mai bune',
'title'=>'Cele mai bune produse',
'description'=>'Cele mai bune produse si articole oferite de [config_title]. [config_title] va ofera o diversitate larga de produse prin gama variata de nuante si materiale ce cu siguranta vor intregi atmosfera locuintei dumneavoastra. Firma noastra este localizata in orasul Cluj-Napoca, judetul Cluj.',
'content'=>'<p>Cele mai bune produse si articole oferite de <strong>[config_title]</strong>. <strong>[config_title] </strong>va ofera o diversitate larga de produse prin gama variata de nuante si materiale ce cu siguranta vor intregi atmosfera locuintei dumneavoastra. Firma noastra este localizata in orasul Cluj-Napoca, judetul Cluj.</p>',
'tag'=>'produse bune',
'header'=>'',
'footer'=>'',
'domainid'=>'1',
'menus'=>'top',
'active'=>'1',
'home'=>'0',
'total'=>'0',
'link'=>'',
'ordon'=>'3',
),
'toateprodusele'=>array(
'pageid'=>'3',
'name'=>'toateprodusele',
'template'=>'all',
'menu'=>'Toate produsele',
'title'=>'Toate produsele',
'description'=>'Toate produsele si articolele oferite de [config_title]. [config_title] va ofera o diversitate larga de produse prin gama variata de nuante si materiale ce cu siguranta vor intregi atmosfera locuintei dumneavoastra. Firma noastra este localizata in orasul Cluj-Napoca, judetul Cluj.',
'content'=>'<p>Toate produsele si articolele oferite de <strong>[config_title]</strong>. <strong>[config_title]</strong> va ofera o diversitate larga de produse prin gama variata de nuante si materiale ce cu siguranta vor intregi atmosfera locuintei dumneavoastra. Firma noastra este localizata in orasul Cluj-Napoca, judetul Cluj.</p>',
'tag'=>'produse',
'header'=>'',
'footer'=>'',
'domainid'=>'1',
'menus'=>'bottom',
'active'=>'1',
'home'=>'0',
'total'=>'0',
'link'=>'',
'ordon'=>'5',
),
'hartasite'=>array(
'pageid'=>'2',
'name'=>'hartasite',
'template'=>'sitemap',
'menu'=>'Harta site',
'title'=>'Harta site',
'description'=>'Pentru un plus de originalitate adus casei dvs va recomandam sa inlocuiti vechile peerdele, care cu siguranta nu-si mai gasesc rostul in casa dvs cu jaluzele orizontale. Aceasta recomandare vine ca urmare a calitatilor incontestabile pe care aceste jaluzele orizontale le au. Printre aceste calitati putem enumera faptul ca puteti alege dintr-o paleta larga de culori cam 180, evident alegere care va fi facuta in functie de cum doriti sa fie casa luminata prin intermediul jaluzele.',
'content'=>'<p>Pentru un plus de originalitate adus casei dvs va recomandam sa inlocuiti vechile peerdele, care cu siguranta nu-si mai gasesc rostul in casa dvs cu <strong>jaluzele</strong>. Aceasta recomandare vine ca urmare a calitatilor incontestabile pe care aceste <strong>jaluzele </strong>le au. Printre aceste calitati putem enumera faptul ca puteti alege dintr-o paleta larga de culori cam 300, evident alegere care va fi facuta in functie de cum doriti sa fie casa luminata prin intermediul jaluzelelor.</p>',
'tag'=>'jaluzele',
'header'=>'',
'footer'=>'',
'domainid'=>'1',
'menus'=>'top|bottom',
'active'=>'1',
'home'=>'0',
'total'=>'0',
'link'=>'',
'ordon'=>'6',
),
'cautari'=>array(
'pageid'=>'4',
'name'=>'cautari',
'template'=>'keyword',
'menu'=>'Cautari',
'title'=>'Cautari',
'description'=>'[config_title] va ofera o diversitate larga de produse prin gama variata de nuante si materiale ce cu siguranta vor intregi atmosfera locuintei dumneavoastra. Firma noastra este localizata in orasul Cluj-Napoca, judetul Cluj.',
'content'=>'<p><strong>[config_title]</strong> va ofera o diversitate larga de produse  prin gama variata de nuante si materiale ce cu siguranta vor intregi  atmosfera locuintei dumneavoastra. Firma noastra este localizata in  orasul Cluj-Napoca, judetul Cluj.</p>',
'tag'=>'',
'header'=>'',
'footer'=>'',
'domainid'=>'1',
'menus'=>'bottom',
'active'=>'1',
'home'=>'0',
'total'=>'0',
'link'=>'',
'ordon'=>'8',
),
'etichete'=>array(
'pageid'=>'9',
'name'=>'etichete',
'template'=>'tag',
'menu'=>'Etichete',
'title'=>'Etichete',
'description'=>'[config_title] va ofera o diversitate larga de produse prin gama variata de nuante si materiale ce cu siguranta vor intregi atmosfera locuintei dumneavoastra. Firma noastra este localizata in orasul Cluj-Napoca, judetul Cluj.',
'content'=>'<p><strong>[config_title]</strong> va ofera o diversitate larga de produse prin gama variata de nuante si materiale ce cu siguranta vor intregi atmosfera locuintei dumneavoastra. Firma noastra este localizata in orasul Cluj-Napoca, judetul Cluj.</p>',
'tag'=>'',
'header'=>'',
'footer'=>'',
'domainid'=>'1',
'menus'=>'bottom',
'active'=>'1',
'home'=>'0',
'total'=>'0',
'link'=>'',
'ordon'=>'9',
),
'search'=>array(
'pageid'=>'10',
'name'=>'search',
'template'=>'search',
'menu'=>'Cauta',
'title'=>'Cauta',
'description'=>'[config_title] va ofera o diversitate larga de produse prin gama variata de nuante si materiale ce cu siguranta vor intregi atmosfera locuintei dumneavoastra. [config_title] este localizata in orasul Cluj-Napoca, judetul Cluj. [category_title]',
'content'=>'<p><strong>[config_title]</strong> va ofera o diversitate larga de produse prin gama variata de nuante si materiale ce cu siguranta vor intregi atmosfera locuintei dumneavoastra. <strong>[config_title]</strong> este localizata in orasul Cluj-Napoca, judetul Cluj. <strong>[category_title]</strong></p>',
'tag'=>'',
'header'=>'<p>Daca ati schimbat deja vechea tamplarie cu termopane, astfel incat sa asigurati un plus de confort casei dvs, va recomandam sa indepartati si perdele si draperii, iar in locul lor sa puneti [config_title] <strong>[category_title]</strong>. Motivul pentru care noi va recomandam [config_title] <strong>[category_title]</strong> este acela ca in primul rand veti aduga o nota de eleganta casei dvs. Pe de alta parte, in functie de materialul din care sunt facute, dvs puteti alege orice culoare pentru [config_title] <strong>[category_title]</strong>, astfel incat sa se asorteze cu mobila pe care o aveti in casa.</p>',
'footer'=>'',
'domainid'=>'1',
'menus'=>'',
'active'=>'1',
'home'=>'0',
'total'=>'0',
'link'=>'',
'ordon'=>'10',
),
'contact'=>array(
'pageid'=>'11',
'name'=>'contact',
'template'=>'default',
'menu'=>'Contact',
'title'=>'Contact',
'description'=>'Oferim o diversitate larga de produse prin gama variata de lemn pe care il detinem. S.C. Rims Productie si Constructii S.R.L, Strada Piata Stefan cel Mare, nr 5/46, Cluj-Napoca, Cluj, luni-vineri 9:30-17:30, 0264-593454 office@rims.ro',
'content'=>'<p>Oferim o diversitate larga de produse prin gama variata de lemn pe care o detinem contruind cu siguranta orice fel de case sau constructii din lemn. Firma noastra este localizata in orasul Cluj-Napoca, judetul <strong>Cluj</strong>.</p>',
'tag'=>'contact, lexundros',
'header'=>'<h2>S.C. Rims Productie si Constructii S.R.L</h2>
<h2>Strada Piata Stefan cel Mare, nr 5/46, Cluj-Napoca, Cluj<br />
Orar: luni-vineri 9:30-17:30 	<br />
Telefon: <b>0264-593454 ; 0264-592317</b> 	<br />
Fax: 0264-593315 	<br />
Email: <b>office@rims.ro</b></h2>',
'footer'=>'<iframe width="610" height="328" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps/ms?ie=UTF8&hl=en&msa=0&msid=208095792978601754017.000489a2db8f5f2f11f3d&source=embed&ll=46.78293,23.601723&spn=0.007347,0.014977&output=embed"></iframe><br /><small><a target="_blank" href="http://maps.google.com/maps/ms?ie=UTF8&hl=en&msa=0&msid=208095792978601754017.000489a2db8f5f2f11f3d&source=embed&ll=46.78293,23.601723&spn=0.007347,0.014977" style="color:#0000FF;text-align:left">Vezi harta mare</a></small>',
'domainid'=>'1',
'menus'=>'top',
'active'=>'1',
'home'=>'0',
'total'=>'0',
'link'=>'',
'ordon'=>'11',
),
'intrebarifrecvente'=>array(
'pageid'=>'17',
'name'=>'intrebarifrecvente',
'template'=>'faq',
'menu'=>'Intrebari frecvente',
'title'=>'Intrebari frecvente',
'description'=>'Intrebari frecvente despre jaluzele verticale, jaluzele personalizate, rulouri, plase insecte si tantari.',
'content'=>'<p>Intrebari frecvente despre case din lemn.</p>',
'tag'=>'jaluzele, intrebari',
'header'=>'',
'footer'=>'',
'domainid'=>'1',
'menus'=>'bottom',
'active'=>'1',
'home'=>'0',
'total'=>'0',
'link'=>'',
'ordon'=>'12',
),
);?>